### ISSUE TITLE
CUDA Error 

### ISSUE THREAD

**Issue by chaitanyamalaviya** [vacancy/NSCL-PyTorch-Release#2]
Hi,

I had been trying to run your code to train a model for the CLEVR dataset but I'm running into an issue. The traceback is below:
```
...
09 15:59:43 Building the model.
09 16:01:08 Writing meter logs to file: "dumps/clevr/desc_nscl_derender/derender-curriculum_all-qtrans_off/meta/run-2019-07-09-15-58-56.meter.json".
09 16:01:08 Building the data loader.
09 16:05:22 Building the data loader. Curriculum = 3/4, length = 1930.
  0%|                                                                                                                                  | 0/60 [00:00<?, ?it/s]Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
ninja: no work to do.
Loading extension module _prroi_pooling...
cudaCheckError() failed : CUDA driver version is insufficient for CUDA runtime version
```

This was the command that I ran: 
```jac-crun 1 scripts/trainval.py --desc experiments/clevr/desc_nscl_derender.py --training-target derender --curriculum all --dataset clevr --data-dir clevr/train --batch-size 32 --epoch 100 --validation-interval 5 --save-interval 5 --data-split 0.95```

I checked that my driver version (410.78) is in fact compatible with the CUDA version (10.0). Moreover, I am able to run other code that relies on PyTorch and uses the GPU. Am I missing something here?

Would appreciate any help, thanks!

**Comment by vacancy** [comment]
Please check the NVCC Version and the CUDA runtime version.

Since I am not sure about your detailed environment information, I would suggest you manually set the LD_LIBRARY_PATH and CUDA_HOME.

**Comment by chaitanyamalaviya** [comment]
Thanks, setting CUDA_HOME did the trick!
